### PR TITLE
Add amygdala and hippocampus from HCP subcortical atlas

### LINKED ISSUE #7: Replace/supplement Schaefer with Yan 2023?
https://github.com/ThomasYeoLab/CBIG/releases/tag/v0.28.3-Fix_parcel_order_Yan2023

### LINKED ISSUE #14: Add hippocampus node to atlas
Stems from #15 (was https://github.com/PennLINC/xcp_d/issues/939).

### PR DESCRIPTION
**Pull request by tsalo**
Closes #14 and closes #7.

Ready to try out.

### CODE REVIEW

**Comment by tsalo** [comment]
Did it work?

**Comment by mattcieslak** [comment]
I'm having issues with my templateflow installation. We may have done ourselves a disservice by not using containers for this whole thing

**Comment by tsalo** [comment]
Darn, the parcel counts in the dseg tsv and json filenames are wrong.

**Comment by mattcieslak** [comment]
This PR got complicated, but I think we're there!

**Pull request merged**
